### ISSUE TITLE
Create spider for Wegmans

### ISSUE THREAD

**Issue by gobfink** [gobfink/Groceries#21]

**Comment by gobfink** [comment]
Splash isn't working for wegmans - no matter what i set the wait delay for it always catches it on the loading screen. 

Switching to an actual browser via selenium.

**Comment by gobfink** [comment]
Found an interesting link on scrapy-selenium: https://github.com/clemfromspace/scrapy-selenium 

I think i'm going to try converting over to that, so that it fits the scrapy framework better

**Comment by gobfink** [comment]
Should be able to detect the names of products being scraped - seems to be hanging excessively for the page to load.

**Comment by gobfink** [comment]
Working through some more complete tests now. Just need to finalize the wegmans runtime docker-compose service via updating the dockerfile, and testing if it needs firefox

**Comment by gobfink** [comment]
It may be worthwhile creating a database to store urls. That way it would be easy to trace which pages were done and which ones weren't

**Comment by gobfink** [comment]
I think the problem is that the page is loading incrementally, and so not all of the items are populated when the page is loaded. I may need to tweak my wait-until statement on my selenium request

**Comment by gobfink** [comment]
Last thing we need to do is choose and track store location, then we will be done.

**Comment by gobfink** [comment]
2020-07-13 19:07:27 [scrapy.core.scraper] ERROR: Error downloading <GET https://shop.wegmans.com/shop/categories/215?page=15>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.8/site-packages/scrapy/core/downloader/middleware.py", line 36, in process_request
    response = yield deferred_from_coro(method(request=request, spider=spider))
  File "/usr/local/lib/python3.8/site-packages/scrapy_selenium/middlewares.py", line 95, in process_request
    WebDriverWait(self.driver, request.wait_time).until(
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py", line 297, in __call__
    element = visibility_of_element_located(self.locator)(driver)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py", line 415, in _find_element
    raise e
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to convert data to an object

Still hits this error - Just putting it up here to log. Running the scraper again seems to make it work just fine
